# Generated by Django 4.2.6 on 2023-10-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=20, verbose_name="Телеграм ID"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="Пользователь"),
                ),
                (
                    "count_of_sintez_tat",
                    models.IntegerField(
                        default=0,
                        verbose_name="Количство синтезированной татарской речи",
                    ),
                ),
                (
                    "count_of_sintez_rus",
                    models.IntegerField(
                        default=0, verbose_name="Количство синтезированной русской речи"
                    ),
                ),
                (
                    "count_of_detect_tat",
                    models.IntegerField(
                        default=0, verbose_name="Количство распознанной татарской речи"
                    ),
                ),
                (
                    "count_of_detect_rus",
                    models.IntegerField(
                        default=0, verbose_name="Количство распознанной русской речи"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, verbose_name="ключ")),
            ],
        ),
        migrations.CreateModel(
            name="Translate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=2048, verbose_name="Текст")),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_translates",
                        to="backend.text",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_text",
                        to="backend.language",
                    ),
                ),
            ],
        ),
    ]
