# Generated by Django 4.2.6 on 2023-10-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="selected_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_with_lang",
                to="backend.language",
                verbose_name="язык Бота",
            ),
        ),
    ]
