# Generated by Django 4.2.6 on 2023-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_telegramuser_selected_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Язык", "verbose_name_plural": "Языки"},
        ),
        migrations.AlterModelOptions(
            name="telegramuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="text",
            options={"verbose_name": "Ключ", "verbose_name_plural": "Ключи"},
        ),
        migrations.AlterModelOptions(
            name="translate",
            options={
                "verbose_name": "Текст на языке",
                "verbose_name_plural": "Тексты на языках",
            },
        ),
        migrations.RenameField(
            model_name="translate",
            old_name="key",
            new_name="text_key",
        ),
        migrations.AlterField(
            model_name="translate",
            name="translate",
            field=models.TextField(max_length=2048, verbose_name="Текст"),
        ),
    ]
